name: on master

on:
  push:
    branches:
      - master

jobs:
  update_notion_property:
    runs-on: ubuntu-latest
    name: Update Notion property
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version and Push tag
        id: version
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: patch
      - name: Update Notion property
        uses: ./
        with:
          gh-username: "szenius"
          gh-token: ${{ secrets.GH_ACCESS_TOKEN }}
          notion-key: ${{ secrets.NOTION_KEY }}
          notion-property-name: "Version Tag"
          notion-update-value: "${{ steps.version.outputs.new_tag }}"
